- name: install nginx, apache and php
  tags: apache, httpd, nginx
  apt:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
      - "{{ nginx_package_name }}"
    state: latest
  #when: ansible_distribution == "Ubuntu"

- name: start and enable apache service
  tags: apache, httpd
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"

#- name: set gzip to off in nginx conf (Ubuntu)
#  tags: nginx, ubuntu, gzip
#  lineinfile:
#    path: /etc/nginx/nginx.conf
#    regexp: '^gzip'
#    line: gzip off;
#  when: ansible_distribution == "Ubuntu"
#  register: nginx_state

- name: restart nginx
  tags: nginx
  service:
    name: "{{ nginx_service_name }}"
    state: restarted
  #when: nginx_state.changed

- name: copy default html file for site
  tags: apache, apache2, httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
