- name: install nginx, apache and php for Ubuntu Server
  tags: apache, apache2, nginx, ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
      - nginx
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: install apache and php for CentOS Server
  tags: apache, httpd, centos
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "CentOS"

- name: start httpd (CentOS)
  tags: centos, apache, httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"

- name: set gzip to off in nginx conf (Ubuntu)
  tags: nginx, ubuntu, gzip
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: '^gzip'
    line: gzip off;
  when: ansible_distribution == "Ubuntu"
  register: nginx_state

- name: restart nginx (Ubuntu)
  tags: nginx, ubuntu
  service:
    name: nginx
    state: restarted
  when: nginx_state.changed

- name: copy default html file for site
  tags: apache, apache2, httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
