apache_package_name: apache2
apache_service: apache2
php_package_name: libapache2-mod-php
nginx_package_name: nginx
nginx_service_name: nginx
ssh_users: "controller simone"
ssh_template_file: sshd_config_ubuntu.j2
