- name: add ssh for simone
  authorized_key:
    user: simone
    key: "ansible ssh key"

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0664
  notify: restart_sshd
